### ISSUE TITLE
Usage on Windows / Mac

### ISSUE THREAD

**Issue by bamarni** [ellotheth/pipethis#11]
Does this tool work on Windows / Mac? If so, could there be executables available in the releases?

Thanks

**Comment by ellotheth** [comment]
Unfortunately I don't have access to a Mac, so I can't test that one. It didn't even occur to me to try it on Windows, because I've never used a "pipe an installer script into PowerShell" installation method there. I can try it out next weekend (I'm currently traveling in Linux-land).

**Comment by ellotheth** [comment]
(For what it's worth, @dennisdegreef has done some development work with `pipethis` on a Mac, so you should at least get a passing test suite on that platform!)

**Comment by dennisdegreef** [comment]
Might be a bit overkill, but TravisCI can build for multiple platforms, including OSX. I could also take a look into integrating pipethis on Homebrew. I have only done this through Homebrew's 'taps'-concept before though.

I'm not too sure about Windows, but I've seen package managers for Windows as well (https://chocolatey.org/). I guess when bash support hits Windows, this should be possible?

I know a project that does build and distribute for multiple platforms, I can look into their build pipeline.
And yes, I did do some development on OSX, works like a charm :)

**Comment by bamarni** [comment]
I'm on Mac too, I wanted to give it a try but couldn't find any example in the doc, do you know any open source tool supporting pipethis?

Anyways thanks for the clarification :)

**Comment by ellotheth** [comment]
As far as I know, nothing's using pipethis yet. I've been using my personal server for testing, and you're welcome to try a test script to see how the identity verification works:

```
$ pipethis https://ramblinations.com/signed.detached
```

You can also run an unsupported script (like the `rvm` installer, or anything similar) with the `--no-verify` flag:

```
$ pipethis --no-verify --inspect https://get.rvm.io
```

[This might be an OSX build](https://github.com/ellotheth/pipethis/files/321815/osxbuild.zip). If you get a chance to try it, would you let me know if it works?

**Comment by dennisdegreef** [comment]
`2016/06/18 17:58:55 Signature verified` :+1:

**Comment by ellotheth** [comment]
Cross-compiling for OSX from Linux is straightforward:

```
$ GOOS=darwin GOARCH=amd64 make dist
```

I'll start pushing up OSX builds for future releases. I don't think it's worth baking into the Makefile.

Closing this for now, and we can revisit Windows 10 if/when Bash support hits. (I know people are already building `apt` implementations, but I'm pretty skeptical that straight shell script installers will Just Work (tm).) Thanks to you both for the research and testing!
